### ISSUE TITLE
[feat]: export to csv

### ISSUE THREAD

**Issue by Balance8** [sadmann7/shadcn-table#200]
### Feature description

Add the ability to export data to csv

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by manaskshatriya** [comment]
Any Update on the feature?

**Comment by sadmann7** [comment]
i will try to put together a demo of it in the weekend

**Comment by manaskshatriya** [comment]
Hey any update?

**Comment by sadmann7** [comment]
Thanks for suggesting the feature.

Wrote a function to export as csv.

```ts
 <Button
        variant="outline"
        size="sm"
        onClick={() =>
          exportTableToCSV(table, {
            filename: "tasks",
            excludeColumns: ["select", "actions"],
          })
        }
      >
        <DownloadIcon className="mr-2 size-4" aria-hidden="true" />
        Export
      </Button>
```

**Comment by yasseralsaidi** [comment]
can we export all filterd data without to do page by page?

**Comment by john093e** [comment]
Hello @yasseralsaidi, I will try to help on the direction to take for your request :)

_Yes_, it is possible to accomplish this task, but not using the CSV export feature from @sadmann7.

**Why?** This would involve considering many different factors. For example, imagine you have a million rows with thousands of columns and many text fields; this would result in a very large file.

**1. Long-running Task:**
In my opinion, this should be handled as a background job. I would use [Inngest](https://www.inngest.com/) for such a task. A background job is necessary because Vercel only runs for a limited amount of time, depending on your account plan and runtime setup.
![Capture-2024-04-21-184448](https://github.com/sadmann7/shadcn-table/assets/22085166/b69a8aff-67e8-4d5c-bbcc-ad9334ef1fc8)

**2. File Size and Memory:** 
Generating a CSV file as a background task requires careful memory management. Although a CSV file is typically light, it can quickly become cumbersome depending on the volume of data to be exported. For this, I would stream the data to a file saved on [Uploadthing](https://uploadthing.com/).
![Capture-2024-04-21-184745](https://github.com/sadmann7/shadcn-table/assets/22085166/440095df-9ddc-48f5-a828-562695e49845)

**3. Task Concurrency:**
Depending on your setup (runtime, etc.), be aware that generating a file takes time and can slow down other users' requests. Again, Inngest would be key to addressing this issue.


**Final Workflow:**
1. A user on your platform requests an export.
2. You save the export request with filters and other data in your database.
3. You start an Inngest flow to generate the file (Papaparse can help to generate the file).
4. Inngest streams the data in chunks to Uploadthing to ensure data is not lost and memory limits are not exceeded.
5. Once the full data set is sent to your file on Uploadthing, you send a notification through your platform or by email to the user with a link to the file located on Uploadthing.

Exporting data to CSV can be quite complex!
