### ISSUE TITLE
Selection persists when pagination and/or filters change

### ISSUE THREAD

**Issue by AndKenneth** [sadmann7/shadcn-table#90]
If I select the first item in the list, when I move to the next page the first item is still selected. I've fixed this in useDataTable in our project by simply adding this

![image](https://github.com/sadmann7/shadcn-table/assets/5133959/e90681f9-2d11-495d-b25a-58076e65ba2e)

Not sure if this is a good approach (notably if I increase the per-page this won't persist already selected items), and I've notice it still happens when I select filters.

**Comment by yasseralsaidi** [comment]
see where the pagination change code and add this:
```table.toggleAllRowsSelected(false);```

**Comment by andresfiloso** [comment]
I'm having the same issue and I'm not being able to fix it.

**Comment by denizalpaslan** [comment]
By default, tanstack table uses row index to keep track of selected rows. You can change that behavior using getRowId callback.

Inside useDataTable hook:

```typescript
const table = useReactTable({
  //...
  getRowId: row => row.id //<replace 'id' with any field you want to use, make sure it is unique.
})
```

If you do it properly, it should start using the unique IDs for each row instead of index, which would solve your issue.

PS: you may want to pass that field as a prop to the hook to make it reusable for different fields.

**Comment by sadmann7** [comment]
thanks @denizalpaslan.

didn't know about that.

if anyone wanna make a pr for it that would be great.

**Comment by sadmann7** [comment]
fixed now
